openapi: "3.1.0"
info:
  title: "Yomi API"
  description: "API for Proyecto Yomi"
  version: "1.0.0"
servers:
  - url: "TBD"
paths:
  /createRole:
    post:
      summary: "Create new Role"
      operationId: "createRole"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Role"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Role"
components:
  schemas:
    Role:
      type: "object"
      properties:
        roleName:
          type: "string"
        roleDescription:
          type: "string"